title: llllogos
timezone: America/New_York
url: http://llllogos.com
description: Online archive of logos, curated by Justin Jay Wang.
collections:
  posts:
    title: Featured
    output: true
  uploads:
    title: Uploads
    output: true
  logos:
    title: Logos
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: featured
- scope:
    path: ''
    type: posts
  values:
    permalink: '/featured/:title/'
    layout: featured
- scope:
    path: ''
    type: logos
  values:
    permalink: '/:title/'
    layout: logo
    designer: 
    country: 
    year: 
    tags: 
    pad: 1
autopages:
  enabled: true
  tags:
    enabled: true
    layouts:
      - autopage_filters.html
    title: ''
  categories:
    enabled: false
  collections:
    enabled: false
pagination:
  enabled: true
  per_page: 120
  permalink: '/:num/'
  title: ''
  limit: 0
  sort_field: 'title'
  sort_reverse: false
  collection: logos
  trail: 
    before: 999
    after: 999
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README*
- '.gitignore'
gems:
- jekyll-paginate-v2
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
twitter:
  username: llllogos
logo: 
markdown: kramdown
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: assets/styles/
  style: compressed
repository: justinjaywang/llllogos
google_analytics: 
date_format: '%B %-d, %Y'
nav:
  header:
  - text: Directory
    link: /
  - text: Featured
    link: /featured/
  - text: About
    link: /about/
